# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('matricula', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diisc_pre', models.IntegerField()),
                ('disc_credito', models.IntegerField()),
                ('aluno_credito_obri', models.IntegerField()),
                ('aluno_credito_let', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('codigo', models.CharField(max_length=30)),
                ('obr_let', models.TextField()),
                ('status', models.TextField()),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coredrca.Credito')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coredrca.Curso')),
                ('disc_pre', models.ManyToManyField(blank=True, to='coredrca.Disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('departamento', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='coredrca.Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('tipo', models.IntegerField()),
                ('departamento', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='coredrca.Departamento')),
            ],
        ),
        migrations.AddField(
            model_name='disciplina',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coredrca.Professor'),
        ),
        migrations.AddField(
            model_name='curso',
            name='secretaria',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='coredrca.Departamento'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='credito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coredrca.Credito'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='disciplinas',
            field=models.ManyToManyField(blank=True, to='coredrca.Disciplina'),
        ),
    ]
